name: Doxygen

on:
  push:
    branches: [ main ]
    
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .

